version: "3"

services:
  tezedge-node:
    image: tezedge/tezedge:v1.6.8
    command: ["--network", "${TEZOS_NETWORK}", "--p2p-port=9732", "--rpc-port=18732", "--websocket-address=0.0.0.0:4927", "--log", "terminal", "file", "--log-file", "/tmp/tezedge/tezedge.log", "--tezos-context-storage", "irmin", "--peer-thresh-low", "60", "--peer-thresh-high", "80"]
    logging:
      # Produce syslogs instead of terminal logs
      driver: "syslog"
      options:
        # Send the logs to syslog (UDP only) server (running on debugger)
        syslog-address: "udp://0.0.0.0:10001"  # Port must match debugger syslog port in 'ports' section
        # Always in same RFC 5424 format (with microseconds precision)
        syslog-format: "rfc5424micro"
    volumes:
      - "${TEZEDGE_VOLUME_PATH}:/tmp/tezedge"
    environment:
      - TEZOS_STORAGE=index-log-size=5_000_000
    ports:
      - "4927:4927"       # node WS port (required only for tezedge)
      - "9732:9732"       # node P2P port
      - "18732:18732"     # node RPC port
      - "3030:3030"       # sandbox launcher port

  explorer:
    image: tezedge/tezedge-explorer:v1.6.7
    environment:
      - SANDBOX=http://${HOSTNAME}:3030
      - DEBUGGER=http://${HOSTNAME}:17732
      # need a better way to provide such information
      - API=[{"id":"rust","type":"tezedge","name":"rust.${HOSTNAME}","http":"http://${HOSTNAME}:18732","p2p_port":9732,"features":[{"name":"ws","url":"ws://${HOSTNAME}:4927"},{"name":"monitoring"},{"name":"resources/system","monitoringUrl":"http://${HOSTNAME}:38732/resources/tezedge"},{"name":"resources/memory","memoryProfilerUrl":"http://${HOSTNAME}:17832"},{"name":"mempool"},{"name":"network"}]},{"id":"ocaml","type":"octez","name":"ocaml.${HOSTNAME}","http":"http://${HOSTNAME}:18733","p2p_port":9733,"features":[{"name":"monitoring"},{"name":"resources/system","monitoringUrl":"http://${HOSTNAME}:38732/resources/ocaml"},{"name":"resources/memory","memoryProfilerUrl":"http://${HOSTNAME}:17832"},{"name":"mempool"},{"name":"network"}]}]
    ports:
      - "80:80"
# volumes:
#   ${TEZEDGE_VOLUME_PATH}:
#     name: tezedge-shared-data
#     # external: false