db_path = "/tmp/volume/debugger_db"
rpc_port = 17732
p2p_message_limit = 10_000_000
log_message_limit = 10_000_000
bpf_sniffer = "/tmp/bpf-sniffer.sock"
keep_db = false

[[nodes]]
name = "tezedge"
# path to search identity at
identity_path = "/tmp/volume/tezedge/identity.json"
# debugger expect the node will listen its p2p incoming connections on this port
# which process earliest will bind a socket on this port, will be considered as the node
# this is an inner port inside docker's virtual network of the node's container
p2p_port = 9732
# debugger will run syslog server on this port
# this is an inner port inside docker's virtual network of the debugger's container
syslog_port = 10001

[[nodes]]
name = "tezos"
identity_path = "/tmp/volume/tezos/data/identity.json"
p2p_port = 9733
syslog_port = 11001
